/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <errno.h>

/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#ifndef _WIN32
#include <unistd.h>
#endif

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif


/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 77
#define YY_END_OF_BUFFER 78
static yyconst short int yy_accept[218] =
    {   0,
        0,    0,   78,   77,   75,    1,   43,   73,   77,   54,
       57,   74,   66,   67,   52,   50,   72,   51,   76,   53,
       29,   65,   40,   44,   39,   27,   68,   69,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       70,   71,   59,   38,    0,   31,   33,    0,    0,    0,
       49,   42,    0,   64,   47,   55,   45,   56,   46,   63,
       62,   48,    0,   29,   60,   35,   37,   36,   61,    0,
       27,    0,    0,   27,   27,   27,   27,    9,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
        0,    0,   34,   30,    0,    0,   28,   58,   27,   27,

       27,   27,   14,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,    0,    0,    0,   32,    0,   27,
       15,   27,   27,   21,   18,   27,   27,   27,   27,   27,
       27,   27,   27,    7,   27,    0,    0,    0,    8,   20,
       27,    0,   27,   27,   13,   19,   27,   27,   27,   10,
        0,    0,   41,   27,    3,    0,    0,   11,    6,   16,
       22,   27,    0,    0,   27,    0,    0,   27,    0,    0,
       12,    0,    0,   17,    0,    0,    0,    0,    0,    0,
        0,    0,    2,   24,   26,    0,    0,    0,    0,   26,
        0,    0,   25,   23,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    4,    0,    5,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,    1,   20,   21,
       22,   23,    1,    1,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       25,    1,   26,   27,   28,    1,   29,   30,   31,   32,

       33,   34,   35,   36,   37,   24,   38,   39,   40,   41,
       42,   43,   24,   44,   45,   46,   47,   48,   49,   24,
       24,   24,   50,   51,   52,   53,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[54] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    1,    1,    1,
        4,    5,    1,    1,    1,    1,    6,    1,    7,    1,
        1,    1,    1,    8,    4,    1,    1,    9,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    1,
        8,    1,    1
    } ;

static yyconst short int yy_base[230] =
    {   0,
        0,    0,  454,  455,  455,  455,  431,   51,   23,  430,
      442,    0,  455,  455,   40,   42,  455,   43,  455,   48,
       50,  455,   50,  428,   51,   52,  398,  455,   57,   64,
       65,   69,   70,   68,   73,   74,   94,   97,  102,   98,
      455,  455,  455,  455,  108,  455,  442,  441,  413,  404,
      455,  455,  434,  455,  455,  455,  455,  455,  455,  455,
      455,  455,  424,   69,  455,  455,  455,  455,  455,    0,
      104,  102,  416,  121,  122,  125,  128,  130,  131,  137,
      132,  138,  147,  154,  149,  157,  156,  159,  160,  165,
      407,  409,  455,  420,  426,  126,  455,  412,  169,  176,

      178,  184,  185,  194,  196,  197,  188,  200,  201,  203,
      205,  221,  222,  223,  399,  396,  422,  455,  382,  225,
      228,  231,  232,  240,  248,  249,  250,  253,  255,  256,
      257,  260,  259,  261,  268,  391,  384,  404,  281,  284,
      287,  271,  288,  289,  292,  293,  299,  296,  300,  304,
      396,  396,  455,  309,  455,   75,   84,  312,  315,  321,
      322,  324,  419,  386,  325,  194,  149,  327,  414,  396,
      328,   79,  331,  337,  408,    0,  108,  399,  341,  406,
      390,   80,  455,  347,    0,  370,  388,  332,  385,    0,
      376,  339,  378,  455,  203,  384,  352,  346,  340,  324,

      361,  348,  342,  325,  283,  272,  270,  253,  239,  228,
      230,  237,  205,  455,  215,  455,  455,  371,  180,  377,
      386,  156,  393,  400,  406,  110,  413,  416,  418
    } ;

static yyconst short int yy_def[230] =
    {   0,
      217,    1,  217,  217,  217,  217,  217,  218,  217,  217,
      217,  219,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  220,  217,  217,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      217,  217,  217,  217,  218,  217,  221,  221,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  217,  217,  222,
      220,  217,  217,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      217,  217,  217,  217,  223,  217,  217,  217,  220,  220,

      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  217,  217,  223,  217,  217,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  217,  217,  217,  220,  220,
      220,  222,  220,  220,  220,  220,  220,  220,  220,  220,
      217,  217,  217,  220,  217,  223,  223,  220,  220,  220,
      220,  220,  217,  217,  220,  223,  223,  220,  224,  217,
      220,  223,  223,  220,  225,  226,  223,  223,  227,  225,
      228,  223,  217,  217,  229,  217,  228,  223,  217,  229,
      217,  223,  217,  217,  223,  217,  217,  217,  217,  217,

      217,  217,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,    0,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  217,  217
    } ;

static yyconst short int yy_nxt[509] =
    {   0,
        4,    5,    6,    4,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,    4,    4,   26,   29,
       30,   26,   31,   26,   26,   26,   32,   26,   33,   34,
       26,   26,   35,   36,   37,   26,   38,   39,   40,   41,
       26,   42,   43,   46,   49,   56,   47,   54,   58,   50,
       60,   55,   70,   57,   59,   61,   63,   70,   64,   62,
       65,   66,   68,   69,   70,   70,   72,   48,   70,   70,
       70,   72,  177,   70,   70,   63,  118,   64,   72,   72,
      118,  118,   72,   72,   72,  118,   81,   72,   72,   75,

       74,   48,   78,   77,   70,   76,   83,   70,   70,   79,
       46,   80,   70,   47,   70,  166,   82,  181,   72,  118,
       96,   72,   72,  188,   84,  167,   72,   97,   72,   85,
       86,   70,   70,   90,   48,   70,  182,   88,   70,   87,
       70,   70,   70,   89,   96,   72,   72,   70,   70,   72,
      100,   97,   72,   99,   72,   72,   72,   70,   48,   70,
      118,   72,   72,   95,   70,  101,   70,   70,  105,   70,
       70,   72,  102,   72,  106,   70,  103,  104,   72,   70,
       72,   72,  108,   72,   72,  173,   70,   53,   70,   72,
      109,  110,  107,   72,   70,   70,  113,  120,   70,  111,

       72,  114,   72,  112,   70,  118,   70,   70,   72,   72,
       70,   70,   72,   70,  118,   70,  124,  196,   72,  121,
       72,   72,  122,  123,   72,   72,  216,   72,  125,   72,
      215,   70,   70,   70,  128,   70,  126,  127,   70,  172,
      129,   70,   70,  131,  130,   72,   72,   72,  214,   72,
       70,  132,   72,  134,  213,   72,   72,  133,   70,  142,
       70,  135,  139,   70,   72,   70,   70,   70,  141,   70,
       70,   70,   72,   72,   72,  212,  140,   72,   70,   72,
       72,   72,  155,   72,   72,   72,  211,  210,  145,  147,
      148,   70,   72,  149,   70,  143,  144,   70,   70,   70,

      150,  146,   70,   70,  209,   72,   70,  156,   72,   70,
       70,   72,   72,   72,   70,  208,   72,   72,  157,   70,
       72,  158,   70,   72,   72,   70,  207,  154,   72,  159,
      160,   70,   70,   72,   70,   70,   72,   70,   70,   72,
      162,  161,  118,  118,  179,   72,   72,   70,   72,   72,
      118,   72,   72,  206,  204,  165,  168,  171,  174,  184,
      203,   72,  178,  189,  202,  184,  192,  201,  200,  195,
      205,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       71,  199,  198,   71,   71,   71,   48,  197,   48,   48,
       48,   48,   48,   48,   48,  117,  193,  117,  194,  117,

      117,  117,  175,  193,  186,  191,  186,  175,  180,  179,
      183,  179,  180,  180,  180,  185,  176,  169,  170,  185,
      185,  187,  169,  187,  190,  190,  190,  164,  163,  153,
      152,  151,  138,  118,  137,  136,  119,  118,   94,  116,
      115,   98,   94,   93,   92,   91,   47,   47,   73,   67,
       52,   51,   44,  217,    3,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  217,  217,  217,

      217,  217,  217,  217,  217,  217,  217,  217
    } ;

static yyconst short int yy_chk[509] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    8,    9,   16,    8,   15,   18,    9,
       20,   15,   26,   16,   18,   20,   21,   29,   21,   20,
       23,   23,   25,   25,   30,   31,   26,    8,   34,   32,
       33,   29,  172,   35,   36,   64,  156,   64,   30,   31,
      172,  182,   34,   32,   33,  157,   34,   35,   36,   30,

       29,    8,   32,   31,   37,   30,   36,   38,   40,   32,
       45,   33,   39,   45,   71,  156,   35,  226,   37,  177,
       72,   38,   40,  182,   37,  157,   39,   72,   71,   37,
       37,   74,   75,   40,   45,   76,  177,   38,   77,   37,
       78,   79,   81,   39,   96,   74,   75,   80,   82,   76,
       75,   96,   77,   74,   78,   79,   81,   83,   45,   85,
      167,   80,   82,  222,   84,   76,   87,   86,   81,   88,
       89,   83,   77,   85,   82,   90,   79,   80,   84,   99,
       87,   86,   84,   88,   89,  167,  100,  219,  101,   90,
       85,   86,   83,   99,  102,  103,   89,   99,  107,   87,

      100,   90,  101,   88,  104,  166,  105,  106,  102,  103,
      108,  109,  107,  110,  195,  111,  102,  195,  104,  100,
      105,  106,  101,  101,  108,  109,  215,  110,  104,  111,
      213,  112,  113,  114,  107,  120,  105,  106,  121,  166,
      108,  122,  123,  110,  109,  112,  113,  114,  212,  120,
      124,  111,  121,  113,  211,  122,  123,  112,  125,  126,
      127,  114,  120,  128,  124,  129,  130,  131,  123,  133,
      132,  134,  125,  126,  127,  210,  122,  128,  135,  129,
      130,  131,  142,  133,  132,  134,  209,  208,  129,  131,
      132,  139,  135,  133,  140,  127,  128,  141,  143,  144,

      135,  130,  145,  146,  207,  139,  148,  142,  140,  147,
      149,  141,  143,  144,  150,  206,  145,  146,  142,  154,
      148,  143,  158,  147,  149,  159,  205,  141,  150,  144,
      147,  160,  161,  154,  162,  165,  158,  168,  171,  159,
      149,  148,  173,  188,  179,  160,  161,  174,  162,  165,
      192,  168,  171,  204,  203,  154,  162,  165,  168,  179,
      202,  174,  173,  184,  201,  184,  188,  200,  199,  192,
      203,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      220,  198,  197,  220,  220,  220,  221,  196,  221,  221,
      221,  221,  221,  221,  221,  223,  193,  223,  191,  223,

      223,  223,  224,  189,  187,  186,  181,  224,  225,  180,
      178,  175,  225,  225,  225,  227,  170,  169,  164,  227,
      227,  228,  163,  228,  229,  229,  229,  152,  151,  138,
      137,  136,  119,  117,  116,  115,   98,   95,   94,   92,
       91,   73,   63,   53,   50,   49,   48,   47,   27,   24,
       11,   10,    7,    3,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  217,  217,  217,

      217,  217,  217,  217,  217,  217,  217,  217
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
#define INITIAL 0
#line 2 "scanner.l"
  int yylineno;

//Keywords
  #define WHILE 1
  #define VOID 2
  #define RETURN 3
  #define MAINFUNC 4
  #define BREAK 5
  #define CONTINUE 7
  #define IF 8
  #define INT 10
  #define CHAR 11
  #define UNSIGNED 12
  #define SIGNED 13
  #define LONG 14
  #define SHORT 15
  #define ELSE 16
  #define FOR 17
  #define STRUCT 18

//Identifier and Constant
  #define ID 20
  #define CONST 21

//Operators
//Comparators
  #define LE 22
  	// Less than equal to
  #define GE 23
  	// Greater than equal to
  #define EQ 24
  	// Check for equality
  #define NE 25
  	// Not equal to check
  #define L 77
  	// Less than
  #define G 78
  	// Greater than

//Logical
  #define OR 26
  #define AND 27
  #define NOT 28

//Assignment
  #define ASS 29
  	//   =	Simple assignment operator.
  #define ADDASS 30
  	// +=	Add AND assignment operator.
  #define SUBASS 31
  	// -=	Subtract AND assignment operator.
  #define MULASS 32
  	// *=	Multiply AND assignment operator.
  #define DIVASS 33
 	// /=	Divide AND assignment operator.
  #define MODASS 34
  	//	%=	Modulus AND assignment operator.

//Arithmetic
  #define PLUS 35
  #define SUB 36
  #define MULT 37
  #define DIV 38
  #define MOD 39
  #define PP 40
  	// ++
  #define MM 41
  	// --

//Bitwise Ops
  #define BA 42
  	// Bitwise and
  #define BO 43
  	// Bitwise or
  #define BC 44
  	// Bitwise complement
  #define OC 45
	//one's complement
  #define LS 46
    // left shift
  #define RS 47
    //right shift

// Miscelaneous tokens
  #define SEMICOLON 53
  #define BA1 54
  	// '(' bracket
  #define BA2 55
  	// ')' bracket
  #define BB1 56
  	// '[' bracket
  #define BB2 57
  	// ']' bracket
  #define BC1 58
  	// '{' bracket
  #define BC2 59
  	//'}' bracket
  #define COMMA 60
  	// ','
  #define Q 61
  	// Quote "
  #define SQ 62
  	// Single Quote '
  #define HEAD 63
  	// Header file
  #define ARR 64
	// Array
  #define SLC 65
	// Single comment '/'
  #define MLCO 66
  	// Multiline Comment Open '/*'
  #define MLCC 67
  	// Multilien Comment Close '*/'
  #define DEF 68
    // Macro
  #define PRINTF 69
  #define SCANF 70
  #define FUNC 71
  #define STRING 72
  #define INTCONST 73
  #define FLOATCONST 74
  #define CHARCONST 75
  #define INVALIDSTRING 76
  #define DOT 80
#line 677 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 133 "scanner.l"

#line 841 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 218 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 455 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 134 "scanner.l"
{yylineno++;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 135 "scanner.l"
return MAINFUNC;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 136 "scanner.l"
return MAINFUNC;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 137 "scanner.l"
return MAINFUNC;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 138 "scanner.l"
return MAINFUNC;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 139 "scanner.l"
return RETURN;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 140 "scanner.l"
return VOID;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 141 "scanner.l"
return BREAK;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 142 "scanner.l"
return IF;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 143 "scanner.l"
return WHILE;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 144 "scanner.l"
return PRINTF;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 145 "scanner.l"
return CONTINUE;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 146 "scanner.l"
return SCANF;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 147 "scanner.l"
return INT;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 148 "scanner.l"
return CHAR;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 149 "scanner.l"
return SIGNED;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 150 "scanner.l"
return UNSIGNED;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 151 "scanner.l"
return LONG;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 152 "scanner.l"
return SHORT;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 153 "scanner.l"
return CONST;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 154 "scanner.l"
return ELSE;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 155 "scanner.l"
return STRUCT;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 157 "scanner.l"
return HEAD;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 159 "scanner.l"
return DEF;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 160 "scanner.l"
return DEF;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 161 "scanner.l"
return DEF;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 163 "scanner.l"
return ID;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 164 "scanner.l"
return ARR;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 165 "scanner.l"
return INTCONST;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 166 "scanner.l"
return FLOATCONST;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 168 "scanner.l"
return INVALIDSTRING;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 170 "scanner.l"
return FUNC;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 172 "scanner.l"
return STRING;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 173 "scanner.l"
return CHARCONST;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 175 "scanner.l"
return LE;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 176 "scanner.l"
return GE;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 177 "scanner.l"
return EQ;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 178 "scanner.l"
return NE;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 179 "scanner.l"
return G;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 180 "scanner.l"
return L;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 182 "scanner.l"
return OR;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 183 "scanner.l"
return AND;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 184 "scanner.l"
return NOT;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 186 "scanner.l"
return ASS;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 187 "scanner.l"
return ADDASS;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 188 "scanner.l"
return SUBASS;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 189 "scanner.l"
return MULASS;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 190 "scanner.l"
return DIVASS;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 191 "scanner.l"
return MODASS;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 193 "scanner.l"
return PLUS;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 194 "scanner.l"
return SUB;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 195 "scanner.l"
return MULT;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 196 "scanner.l"
return DIV;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 197 "scanner.l"
return MOD;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 198 "scanner.l"
return PP;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 199 "scanner.l"
return MM;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 201 "scanner.l"
return BA;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 202 "scanner.l"
return BO;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 203 "scanner.l"
return OC;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 204 "scanner.l"
return LS;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 205 "scanner.l"
return RS;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 207 "scanner.l"
return SLC;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 208 "scanner.l"
return MLCO;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 209 "scanner.l"
return MLCC;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 211 "scanner.l"
return SEMICOLON;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 212 "scanner.l"
return BA1;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 213 "scanner.l"
return BA2;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 214 "scanner.l"
return BB1;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 215 "scanner.l"
return BB2;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 216 "scanner.l"
return BC1;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 217 "scanner.l"
return BC2;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 218 "scanner.l"
return COMMA;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 219 "scanner.l"
return Q;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 220 "scanner.l"
return SQ;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 221 "scanner.l"
;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 222 "scanner.l"
return DOT;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 223 "scanner.l"
ECHO;
	YY_BREAK
#line 1309 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 218 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 218 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 217);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef _WIN32
#include <unistd.h>
#else
#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 223 "scanner.l"


//Data Structure for the symbol and constant table
struct symbol
{
	char token[100];	// Name of the token
	char type[100];		// Token type: Identifier, string constant, floating point constant etc
}symbolTable[100000], constantTable[100000];

int i=0; // Number of symbols in the symbol table
int c=0; // Number of constants in the constant table

//Insert function for symbol/constant table
void symbolInsert(struct symbol table[], int index, char* tokenName, char* tokenType)
{
  strcpy(table[index].token, tokenName);
  strcpy(table[index].type, tokenType);
}

int main(void)
{
  int newToken, // The current token being processed
      j,k, // Iterators
      ba_c=0,ba_o=0,ba_l, // Number of open and close paranthesis, last line where the open parantesis was used
      bb_o=0,bb_c=0,bb_l, // Number of open and close square braces,  last line where the open sqaure brace was used
      bc_o=0,bc_c=0,bc_l, // Number of open and close curly braces,  last line where the open curly brace was used
      rep=0; // Flag to denote whether the current token is already in symbol table

  //Taking the input program
  yyin= fopen("test.c","r");

  //Reading a single token from the program
  newToken = yylex();
  printf("\n");

  int mlc=0, // Flag to denote whether current token is part of a multiline comment
      slcline=0, // Line number of the single line comment
      mlcline; // Starting line number of multi line comment

  while(newToken)
  {
    rep = 0;

    if(yylineno==slcline) // If token belongs to a single line comment, ignore all the tokens
    {
      newToken=yylex();
      continue;
    }

    for(k=0;k<i;k++) // Checking whether token already exists in symbol table
    {
      if(!(strcmp(symbolTable[k].token,yytext)))
      {
        rep = 1;
        break;
      }
    }

    for(k=0;k<c;k++) // Checking whether token already exists in constant table
    {
      if(!(strcmp(constantTable[k].token,yytext)))
      {
        rep = 1;
        break;
      }
    }

    if(ba_c > ba_o)
      printf("\n-------------ERROR : UNMATCHED ')' at Line %d------------------\n", yylineno);

    if(bb_c>bb_o)
      printf("\n-------------ERROR : UNMATCHED ']' at Line %d------------------\n", yylineno);

    if(bc_c>bc_o)
      printf("\n-------------ERROR : UNMATCHED '}' at Line %d------------------\n", yylineno);

    if(rep==0 && newToken!=65 && newToken!=66 && newToken!=67 && mlc==0)
    {
      strcpy(symbolTable[i].token,yytext);
    }

    if(newToken ==1 && mlc==0)
    {
      printf("%s\t\tWhile Loop----------Line %d\n",yytext,yylineno);
    }

    else if(newToken ==4 && mlc==0)
    {
      printf("%s\t\tMain function----------Line %d\n",yytext,yylineno);
    }

    else if(newToken ==8 && mlc==0)
    {
      printf("%s\t\tIf statement----------Line %d\n",yytext,yylineno);
    }

    else if(newToken ==16 && mlc==0)
    {
      printf("%s\t\tElse statement----------Line %d\n",yytext,yylineno);
    }

    else if(newToken ==17 && mlc==0)
    {
      printf("%s\t\tFor Loop----------Line %d\n",yytext,yylineno);
    }

    else if(newToken ==18 && mlc==0)
    {
      printf("%s\t\tStruct definition/declaration----------Line %d\n",yytext,yylineno);
    }

    else if(((newToken>=1 && newToken<=15)) && mlc==0) // Keywords
    {
      printf("%s\t\tKeyword----------Line %d\n",yytext,yylineno);
    }

    else if(newToken==20 && mlc==0) // Identifiers
    {
      if(rep == 0)
      {	symbolInsert(symbolTable, i, yytext, "ID");
      	i++;
      }
      printf("%s\t\tIdentifier----------Line %d\n",yytext,yylineno);
    }

    else if(newToken==73 && mlc==0)
    {
      if(rep==0)
      {
       symbolInsert(constantTable, c, yytext, "int");
       c++;
      }
      printf("%s\t\tInteger Constant----------Line %d\n",yytext,yylineno);
    }

    else if(newToken==74 && mlc==0)
    {
      if(rep==0)
      {
       symbolInsert(constantTable, c, yytext, "float");
       c++;
      }
      printf("%s\t\tFloating Point Constant----------Line %d\n",yytext,yylineno);
    }

    else if(((newToken>=22 && newToken<=25)||(newToken>=77 && newToken<=78)) && mlc==0)
    {
      printf("%s\t\tComparision Operator----------Line %d\n",yytext,yylineno);
    }

    else if(newToken>=26 && newToken<=28 && mlc==0)
    {
      printf("%s\t\tLogical Operator----------Line %d\n",yytext,yylineno);
    }

    else if(newToken>=29 && newToken<=34 && mlc==0)
    {
      printf("%s\t\tAssignment Operator----------Line %d\n",yytext,yylineno);
    }

    else if(newToken>=35 && newToken<=41 && mlc==0)
    {
      printf("%s\t\tArithmetic Operator----------Line %d\n",yytext,yylineno);
    }

    else if(newToken>=42 && newToken<=47 && mlc==0)
    {
      printf("%s\t\tBitwise Operator----------Line %d\n",yytext,yylineno);
    }

    else if(((newToken>=53 && newToken<=62)||newToken==80) && mlc==0)
    {
      if(newToken==54)
      {
        ba_o++;
	    ba_l = yylineno;
      }
      if(newToken==55)
        ba_c++;
      if(newToken==56)
      {
        bb_o++;
        bb_l = yylineno;
      }
      if(newToken==57)
        bb_c++;
      if(newToken==58)
      {
        bc_o++;
        bc_l = yylineno;
      }
      if(newToken==59)
        bc_c++;
      printf("%s\t\tSpecial Character----------Line %d\n",yytext,yylineno);
    }

    else if(newToken==63 && mlc==0)
    {
      printf("%s\t\tHeader----------Line %d\n",yytext,yylineno);
    }

    else if(newToken==64 && mlc==0)
    {
      char id[100] = "";
      for(int t = 0; ; t++)
      {
        if(yytext[t] == '[')
          break;
        id[t] = yytext[t];
      }

      for(k=0;k<i;k++) // Checking whether token already exists in symbol table
      {
      	if(!(strcmp(symbolTable[k].token,id)))
      	{
        	rep = 1;
       		break;
      	}
      }

      if(rep == 0)
      {
        symbolInsert(symbolTable, i, id, "ID");
      	i++;
      }
      printf("%s\t\tArray Identfier----------Line %d\n",yytext,yylineno);
    }

    else if(newToken==65 && mlc==0)
    {
      printf("%s\t\tSingle Line Comment----------Line %d\n",yytext,yylineno);
      slcline=yylineno;
    }

    else if(newToken==66)
    {
      mlc=1;
      printf("%s\t\tMulti Line Comment Start----------Line %d\n",yytext,yylineno);
      mlcline = yylineno;

    }

    else if(newToken==66 && mlc==1)
    {
      printf("%s\t\tNested multi Line Comment Start----------Line %d\n",yytext,yylineno);
    }

    else if(newToken==67 && mlc==1)
    {
      mlc=0;
      printf("%s\t\tMulti Line Comment End----------Line %d\n",yytext,yylineno);
      mlcline=0;
    }

    else if(newToken==67 && mlc==0)
      printf("\n---------------ERROR : UNMATCHED NESTED END COMMENT-------------\n");

    else if(newToken==68 && mlc==0)
    {
      printf("%s\t\tPreprocessor Directive----------Line %d\n",yytext,yylineno);
      newToken=yylex();
      continue;
    }

    else if(newToken>=69 && newToken<=70 && mlc==0)
    {
      printf("%s\t\tPre Defined Function----------Line %d\n",yytext,yylineno);
    }

    else if(newToken==71 && mlc==0)
    {
      char id[100] = "";
      for(int t = 0; ; t++)
      {
        if(yytext[t] == '(')
          break;
        id[t] = yytext[t];
      }

      for(k=0;k<i;k++) // Checking whether token already exists in symbol table
      {
      	if(!(strcmp(symbolTable[k].token,id)))
      	{
        	rep = 1;
       		break;
      	}
      }

      if(rep == 0)
      {
        symbolInsert(symbolTable, i, id, "ID");
      	i++;
      }

      printf("%s\t\tUser Defined Function----------Line %d\n",yytext,yylineno);
    }

    else if(newToken==72 && mlc==0)
    {
      if(rep==0)
      {
       symbolInsert(constantTable, c, yytext, "string");
       c++;
      }
      printf("%s\t\tString literal----------Line %d\n",yytext, yylineno);
    }

    else if(newToken==75 && mlc==0)
    {
      if(rep==0)
      {
       symbolInsert(constantTable, c, yytext, "char");
       c++;
      }
      printf("%s\t\tCharacter Constant----------Line %d\n",yytext,yylineno);
    }

    else if(newToken==76 && mlc==0)
    {
	printf("\n--------------------ERROR : INCOMPLETE STRING starting at Line %d------------\n",yylineno);
    }

    newToken=yylex();
  }

  if(mlc==1)
    printf("\n--------------------ERROR : UNMATCHED COMMENT starting at Line %d------------\n",mlcline);

  if(ba_c<ba_o)
    printf("\n--------------------ERROR : UNMATCHED '(' at Line %d ------------------------\n",ba_l);

  if(bb_c<bb_o)
    printf("\n--------------------ERROR : UNMATCHED '[' at Line %d ------------------------\n",bb_l);

  if(bc_c<bc_o)
    printf("\n--------------------ERROR ! UNMATCHED '{' at Line %d ------------------------\n",bc_l);

  printf("\n------------Symbol Table---------------------\n\nSNo\tToken\t\tAttribute\n\n");

  for(j=0;j<i;j++)
    printf("%d\t%s\t\t< %s >\t\t\n",j+1,symbolTable[j].token,symbolTable[j].type);

  printf("\n------------Constant Table---------------------\n\nSNo\tToken\t\tAttribute\n\n");

  for(j=0;j<c;j++)
    printf("%d\t%s\t\t< %s >\t\t\n",j+1,constantTable[j].token,constantTable[j].type);

  return 0;
}

int yywrap(void)
{
	return 1;
}
